name: Http middleware CI

on:
  push:
    branches: ["main"]
    paths: ["middleware/http/**"]
  pull_request:
    branches: ["main"]
    paths: ["middleware/http/**"]
  workflow_dispatch:

jobs:
  ci-http-middleware:
    name: Http middleware
    uses: Clarilab/workflows/.github/workflows/go-backend.yaml@main
    with:
      work_dir: middleware/http